apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
spec:
  selector:
    matchLabels:
      app: node-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: node-web-app
        version: 1.1.9
    spec:
      containers:
      - name: node-web-app
        image: __IMAGE__
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: node-web-app-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
  namespace: node-web-project
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: node-web-app
